# Site settings
email: libertysowl@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Liberty's Owl
description: Heritage of Freedom.
url: www.libertysowl.com
twitter_username: @libertysowl
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
