---
title: East Coast Kelly
description: Helping moms simplify life at home.
author: 
navbar-links:
  Popular: popular
  Course: https://kellymbriggs.github.io/course/
  Connect:
  - About me: https://kellymbriggs.github.io/aboutme/
  - Contact: https://kellymbriggs.github.io/contact/
avatar: "/assets/img/Headshot.jpg"
round-avatar: true
social-network-links:
  email: eastcoastkellyb@gmail.com
  facebook: kelly.briggs
  instagram: eastcoastkelly
  rss: true
share-links-active:
  twitter: true
  facebook: true
  vk: false
url-pretty: www.eastcoastkelly.com
link-tags: true
excerpt_length: "50"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
title-separator: "-"
date_format: "%B %-d, %Y"
timezone: America/Vancouver
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
    readtime: false
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
exclude:
- vendor/bundle
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
plugins:
- jekyll-paginate
- jekyll-sitemap
