# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (<username>.github.io) then use these settings:
#url: "http://<username>.github.io"
#baseurl: ""

# If you are building a GitHub project page then use settings similar to mine:
url: "http://daattali.github.io/beautiful-jekyll"
baseurl: "/beautiful-jekyll"

# --- Header meta --- #
# Brief name and description of the site
name: Beautiful Jekyll by Dean Attali
description: Quickly build a beautiful Jekyll website

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Vancouver"
markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 5

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# List of links in the navigation bar
navbar-links:
  Home: ""
  About Me: "aboutme"
  Contact: "contact"
  Blog: "blog"
  Error page: "nothing"
  
# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dean Attali
  email: "daattali@gmail.com"
  facebook: daattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali"
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "deanattali.com/beautiful-jekyll" 
 
# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
