###########################################################
### Welcome to Beautiful Jekyll!                         #
### This config file is meant for settings that affect   #
### your entire website.                                  #
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: harishsarma_v

# Your name to show in the footer
author: Harish Sarma

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "/"
  About Me / Contact: "aboutme"
  Projects: "projects"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn Markdown: "https://www.markdowntutorial.com/"
  
future: true

################
# --- Logo --- #
################

# Avatar image for the navigation bar
avatar: "assets/img/sblack.jpg"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "harishsarma.v@gmail.com"
  github: harishsarmav
  twitter: harishsarma_v
  reddit: Relevant-Plantain615
  linkedin: "Harish Sarma Velavalapalli"
  instagram: i_am_harishsarma

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  reddit: true
  whatsapp: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"
# Add the website title to the title of every page
title-on-all-pages: true
# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
# Excerpt settings
# Excerpt settings
excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false
# The keywords to associate with your website, for SEO purposes
# Keywords for SEO
#keywords: "my,list,of,keywords"

##################################
# --- Colors / Background Image --#
##################################

# Personalize the colors in your website
page-col: "#F5F5F5"
text-col: "#333333"
link-col: "#1E90FF"
hover-col: "#1C86EE"
navbar-col: "#FFFFFF"
navbar-text-col: "#333333"
navbar-border-col: "#DDDDDD"
footer-col: "#F5F5F5"
footer-text-col: "#666666"
footer-link-col: "#1E90FF"
footer-hover-col: "#1C86EE"

# Navbar and footer background images
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Mobile theme color
#mobile-theme-col: "#0085A1"

# Custom CSS and JS files
#site-css:
#  - "/assets/css/custom-styles.css"
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- Web Analytics Section --- #
#################################

# Google Analytics or other tracking settings
#gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

# Disqus settings for comments
#disqus: ""

################
# --- Misc --- #
################

# Ruby Date Format for post dates
date_format: "%B %-d, %Y"

# Timezone setting
timezone: "Asia/Kolkata"



# Default permalink structure
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values
collections:
  posts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      show-share: true
      comments: true
      social-share: true

  -
    scope:
      path: ""
    values:
      layout: "page"
      show-share: true

# Excluded files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# Jekyll plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
