###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: FurSquared

# Short description of your site
description: "FurSquared 2024: World of Innovation"

# Your name to show in the footer
author: Two Ferrets Co. dba FurSquared

url: "https://fursquared.com"

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Activities:
    - Schedule: 'programming'
    - Artist Alley: "artist-alley"
    - Dance Events: "dance-events"
    - Dealer's Den: "dealers"
    - STI Testing: "sti-testing"
    - Video Games: "video-games"
  Information:
    - About: "about"
    - Conbook: "assets/FurSquared_2024_Conbook.pdf"
    - Guests of Honor: 'goh'
    - Hotel: "hotel"
    - Code of Conduct: "code-of-conduct"
    - Covid Policy: "covid-policy"
    - Photos: "https://fursquared.smugmug.com/"
    - Poster: "poster"
    - Volunteer: "volunteer"
  Dealers and Artists:
    - Artist Alley: "artist-alley"
    - Dealer's Den: "dealers"
    - Dealer's Gallery: "https://dealers.fursquared.com"
    - Dealing At F2: "dealing-at-f2"
    - Dealer Code of Conduct: "dealer-coc"
  Contact Us: "contact"
  Register: "registration"


################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
#avatar: "/assets/img/2024/Avatar-for-Twitter-Temp.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: false

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
# title-img: /assets/img/2024/header-logo.png


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "info@fursquared.com"
  github: fursquared
  twitter: fursquared
  mastodon: mastodon.furrycon.social/@fursquared
  telegram: fursquaredchat
  discord: Tzhc4KCXre
  rss: true
  bluesky: fursquared.com
#  facebook: deanattali
#  patreon: DeanAttali
#  youtube: "@daattali"
#  medium: yourname
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  calendly: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: FurSquared Website RSS Feed

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  mastodon: true
  facebook: false
  linkedin: false
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "FurSquared.com"

# Add the website title to the title of every page
title-on-all-pages: true

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: false

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#231d41"
navbar-text-col: "#FFFFFF"
navbar-logo-col: "#FFFFFF"
navbar-border-col: "#FFFFFF"
navbar-text-hover-col: "#FFFFFF"
navbar-hover-bg-col: "#342B6D"

page-col: "#342B6D"
header-col: "#FCD41B"
page-text-col: "#FFFFFF"
link-col: "#D11C5D"
hover-col: "#D11C5D"
selection-col: "#692800"

button-col: "#000000"
button-bg-col: "#FCD41B"
button-hover-col: "#000000"
button-bg-hover-col: "#FFE020"

footer-col: "#231d41"
footer-text-col: "#FFFFFF"
footer-link-col: "#D11C5D"
footer-icon-col: "#342B6D"
footer-icon-fill-col: "#FFFFFF"
footer-icon-hover-col: "#FFFFFF"
footer-icon-fill-hover-col: "white"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"
blog-img: "/assets/img/2024/Avatar-for-Twitter-Temp.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- Web Analytics Section --- #
#################################

# Fill in your Google Analytics tag ID (or "Measurement ID") to track your website usage
gtag: "UA-175189175-1"

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- deprecated
# As of July 2023 this is no longer supported by Google! If you are still using `google_analytics`,
# you should switch to using the `gtag` field above instead.
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- Comments --- #
####################

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use CommentBox, sign up for a Project ID on https://commentbox.io
#commentbox: "" # Project ID, e.g. "5694267682979840-proj"

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository" and "branch".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well)
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository,
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below
# See more details about giscus and each of the following parameters at https://giscus.app
#giscus:
#  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  repository-id: # ID of your repository, retrieve this info from https://giscus.app
#  category: Announcements # Category name of your GitHub Discussion posts
#  category-id: # ID of your category, retrieve this info from https://giscus.app
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

# TOC Settings
#toc:
#  min_level: 1
#  max_level: 3
#  list_class: toc
#  list_class: toc__list
#  sublist_class: toc__sublist

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

