baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Real Sam I Am"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = ""
author = "Sam Edwardes"
description = "Real Sam I Am - a blog by Sam Edwardes"
profilePicture = "img/favicon.ico"
keywords = ""
favicon = "favicons/"
customCss = ["css/table.css"]
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/SamEdwardes"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/TheReaLSamlam"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/samedwardes/"

[[params.socialIcons]]
icon = "fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/channel/UCkXD_pR2bYGOyf8Eh6T_BNw"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:edwardes.s@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Data Science"
  weight = 400
  identifier = "data-science"
  url = "/data-science/"

  [[menu.main]]
  name = "Outdoors"
  weight = 500
  identifier = "outdoors"
  url = "/categories/outdoors/"

  [[menu.main]]
  name = "Tags"
  weight = 600
  identifier = "tags"
  url = "/tags/"