[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.58.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.58.3"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
  
[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"