name: ds_base_tmp
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.9.0=py37_0
  - altair=4.1.0=py_1
  - appdirs=1.4.3=py37h28b3542_0
  - appnope=0.1.0=py37_0
  - asn1crypto=1.3.0=py37_0
  - astor=0.8.0=py37_0
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - c-ares=1.15.0=h1de35cc_1001
  - ca-certificates=2020.4.5.2=hecda079_0
  - certifi=2020.4.5.2=py37hc8dfbb8_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - colorama=0.4.3=py_0
  - conda-package-handling=1.6.0=py37h1de35cc_0
  - cryptography=2.8=py37ha12b0ac_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - flake8=3.8.2=py_0
  - flask=1.1.2=py_0
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.2=py37_0
  - gitdb=4.0.2=py_0
  - gitpython=3.1.1=py_1
  - google-pasta=0.2.0=py_0
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.10.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - idna=2.8=py37_0
  - importlib-metadata=1.6.0=py37_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.1.4=py_0
  - jupyterlab-git=0.20.0=py_1
  - jupyterlab_server=1.1.4=py_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37h04f5b5a_0
  - lazy-object-proxy=1.4.3=py37h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.11.4=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - lightgbm=2.3.0=py37h0a44026_0
  - llvm-openmp=10.0.0=h28b9765_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h9aa3819_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mypy_extensions=0.4.3=py37_0
  - nbconvert=5.6.1=py37_0
  - nbdime=2.0.0=py_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_0
  - nodejs=10.13.0=h0a44026_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h3304bdc_1
  - openssl=1.1.1g=h0b31af3_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py37h6c726b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pathspec=0.7.0=py_0
  - patsy=0.5.1=py37_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=20.0.2=py37_1
  - plotly=4.8.1=py_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.11.4=py37h0a44026_0
  - ptyprocess=0.6.0=py37_0
  - pycodestyle=2.6.0=py_0
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.19=py37_0
  - pyflakes=2.2.0=py_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyrsistent=0.16.0=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_2
  - python-dateutil=2.8.1=py_0
  - python.app=2=py37_10
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyzmq=18.1.1=py37h0a44026_0
  - readline=7.0=h1de35cc_5
  - regex=2020.5.14=py37haf1e3a3_0
  - requests=2.22.0=py37_1
  - retrying=1.3.3=py37_2
  - ruamel_yaml=0.15.87=py37h1de35cc_0
  - scikit-learn=0.22.1=py37h27c97d8_0
  - scipy=1.4.1=py37h9fa6033_0
  - seaborn=0.10.1=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - smmap=3.0.2=py_0
  - sqlite=3.31.1=ha441bb4_0
  - statsmodels=0.11.1=py37haf1e3a3_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - toml=0.10.0=py37h28b3542_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h1de35cc_1
  - tqdm=4.42.1=py_0
  - traitlets=4.3.3=py37_0
  - typed-ast=1.4.1=py37h1de35cc_0
  - typing_extensions=3.7.4.1=py37_0
  - urllib3=1.25.8=py37_0
  - vega_datasets=0.8.0=py_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3

